# Generated by Django 3.1.7 on 2021-04-05 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
