# Generated by Django 3.1.7 on 2021-04-05 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0004_auto_20210405_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hops',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hops', to='beer.beer'),
        ),
        migrations.AlterField(
            model_name='malts',
            name='beer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='malts', to='beer.beer'),
        ),
    ]
